ignoredSettings:
  - terminal.integrated.profiles.windows
  - terminal.integrated.profiles.linux
  - terminal.integrated.defaultProfile.windows
  - terminal.integrated.defaultProfile.linux
  - window.newWindowProfile
  - biome.lsp.bin
resources:
  - extensions
  - keybindings
  - settings
  - snippets
  - tasks
additionalFiles:
  - ~/.copilot
  - ~/.claude
